### ISSUE TITLE
7.6: broken if no beModule or feModule

### ISSUE THREAD

**Issue by jousch** [FriendsOfTYPO3/extension_builder#21]
https://github.com/FriendsOfTYPO3/extension_builder/commit/1343fad59f642dd010c4a7e5e4a5bd073ea3db99

**Comment by nicodh** [comment]
Hmm, I can't reproduce this. Can you give more details? I tried: creating a new extension without Plugin and BE Module. Saved it. Openend it again. Saved again - no error.
The code in the  foreach ($extension->getPlugins() as $plugin) etc. is just not executed if there are noc plugins...

**Comment by rvock** [comment]
I can reproduce this issue. When there is no backend module, saving fails.

```
Extension could not be saved: Could not create public resources folder, error: PHP Warning: Invalid argument supplied for foreach() in [...]extension_builder/Classes/Service/FileGenerator.php line 628
```

The problem is, that the FileGenerator tries to iterate over `$this->extension->getBackendModules()` but the property is null:
https://github.com/FriendsOfTYPO3/extension_builder/blob/3563ee4cfd0dc88f020e0437c87be73ce698b4a2/Classes/Service/FileGenerator.php#L631
https://github.com/FriendsOfTYPO3/extension_builder/blob/3563ee4cfd0dc88f020e0437c87be73ce698b4a2/Classes/Domain/Model/Extension.php#L137
