### ISSUE TITLE
syntax error and reformating

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#290]
... In file `EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager`.
After `GeneralUtility::writeFile(...);` was a wrong bracket `)` instead of `}`.
```
    /**
     * @param \EBT\ExtensionBuilder\Domain\Model\Extension $extension
     * @param array $codeTemplateRootPaths
     *
     * @return void
     * @throws \Exception
     */
    public function createInitialSettingsFile($extension, $codeTemplateRootPaths)
    {
        GeneralUtility::mkdir_deep($extension->getExtensionDir(), self::SETTINGS_DIR);
        $settings = @file_get_contents($codeTemplateRootPaths[0] . 'Configuration/ExtensionBuilder/settings.yamlt');
        if ($settings) {
            $settings = str_replace(
                '{extension.extensionKey}',
                $extension->getExtensionKey(),
                $settings
            );
            $settings = str_replace(
                '{f:format.date(format:\'Y-m-d\\TH:i:s\\Z\',date:\'now\')}',
                date('Y-m-d\TH:i:s\Z'),
                $settings
            );
            GeneralUtility::writeFile(
                $extension->getExtensionDir() . self::SETTINGS_DIR . 'settings.yaml',
                $settings
            );
        }
    }
```

**Comment by DavidBruchmann** [comment]
in extension_builder version 9.10.3, never looked up in other versions yet.

**Comment by DavidBruchmann** [comment]
In the current dev-branch the if-statement is missing and the problem therefore gone already.

**Comment by nicodh** [comment]
Can you please be a bit more verbose?
" In file EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager.
After GeneralUtility::writeFile(...); was a wrong bracket ) instead of }."
Do you mean here?https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Configuration/ExtensionBuilderConfigurationManager.php#L275 ? Can't see what you means.

"In the current dev-branch the if-statement is missing and the problem therefore gone already."
which if-statement do you mean? There are only 2 commits between release 9.10.3 and current master. No removed if-statement.

**Comment by DavidBruchmann** [comment]
ohh being very sorry, then it was my own syntax error.  
Had luckily still a comment in the method, so I knew I hacked there a bit.  
Don't know why I made there changes in detail, but have some more complicated things, where extension_builder is looking broken and regrettable useless.
