### ISSUE TITLE
uploadfolder in ext_emconf.php has no value

### ISSUE THREAD

**Issue by nicodh** [FriendsOfTYPO3/extension_builder#298]
It seems it's not enough anymore just to use a boolean variable in fluid and expect the value written as "true" or "false".

On the other hand: do we need that flag anymore?
According to https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html it needs a folder uploads/tx_[extKey-with-no-underscore]  but afaik the uploads folder should not be used since the introduction of FAL
So I would suggest to remove the whole "uploadfolder" stuff

**Comment by simonschaufi** [comment]
cleanup :heavy_check_mark:

**Comment by liayn** [comment]
> On the other hand: do we need that flag anymore?
> According to https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html it needs a folder uploads/tx_[extKey-with-no-underscore] but afaik the uploads folder should not be used since the introduction of FAL
> So I would suggest to remove the whole "uploadfolder" stuff

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html
**The array key :php:`uploadfolder` in extensions :file:`ext_emconf.php` files is obsolete and ignored.**

**Comment by liayn** [comment]
Fixed this straight in the v10 branch

**Comment by zeichensatz** [comment]
@liayn In the v10 branch you now removed all stuff connected with uploading files not only the entry in the ext_emconf.php.
Parts of the stuff (i.e. enctype="multipart/form-data" in New.html, Create.html) might still very helpful to some people (like me), when it comes to FE plugins. There might even some cases, where it will be helpful in a backend module, I guess.

**Comment by liayn** [comment]
Maybe I misunderstood the code then there, but it said that file-upload is not implemented in extension_builder, so I removed it. If I got that wrong, lets revert those parts of course.

**Comment by simonschaufi** [comment]
In my opinion we should not add features that people _might_ find helpful but basic functionality to kickstart an extension. I would rather add the broken fileupload completely than adding only parts and let the user do the rest.

**Comment by zeichensatz** [comment]
@simonschaufi well, I do understand your approach even though I don't agree from my point of view as a non professional. 
The issue was starting about the upload flag in ext_emconf.php. I was just surprised, that the changes of @liayn also deleted a part, which was helpful to me once. Nobody was talking about "adding a feature that people _might_ find helpful" as you say. It was about deleting a feature.
Well, I would be happy, if someone could add a "totally functional file upload". My knowledge is too low, to do it myself.
BTW: When it comes to file upload in TYPO3, people like to reference to the link you mentioned. But did you try it recently? The example is outdated since years and I was not able to get it working. I also tested a promising fork but that was not working well too. Because the example is quite complex (at least for me; my fault, I know), it's not an easy starting point for people, which are trying hard to learn some basic techniques in TYPO3 extension programming.

**Comment by simonschaufi** [comment]
I'm surprised that TYPO3 has no out of the box provided solution for file upload. That is my biggest pain point in extbase.Before extension builder provides a half solution, @liayn just removed it completely which is ok in my opinion

**Comment by liayn** [comment]
Lets be clear about my change:
I removed the properties "needsUploadFolder" from DomainObject and AbstractProperty. Those were there to indicate that an upload folder might be needed. On saving the extension "Notice: File upload is not yet implemented." was sent to the developer.
So the removed code basically does nothing except issuing this error message.
I removed the enctype in Fluid as well. There is no need to generate this. As a web developer dealing with file uploads I assume you have the basic knowledge about HTML and forms and what enctypes are needed when. This has absolutely nothing to do with Extbase. Besides that, you almost never want form-based uploads to be stored in the old "uploads" folder (the one created by the flag in emconf) because you want those files in FAL and accessible for BE users.

Regarding file upload:
I thought about integrating the example of Helmut Hummel multiple times, but I came to the conclusion that this the example is too simple for real projects. Yes you always have to deal with FAL integration matters and stuffing things into the models correctly, this is well covered in the example. But real projects mostly require things like:

- cropping of avatar images in JS and sending the cropped version. The example then does not work anymore because mostly you get a base64 encoded image now. Custom handling on the server side is necessary.
- uploads for documents need a progress bar or similar, or at least advanced error checking. The example can't help you with that because upload happens via JS API in the Browser and needs a dedicated endpoint on the server. Again custom handling is required.
- ...

**Comment by zeichensatz** [comment]
@simonschaufi, well I'm also missing a simple file upload solution (especially for the FE).
@liayn, thanks for your detailed comment and your patience. As you might have realized already, we both are talking on a completely different level of knowledge. It never would come into my mind to call myself a "web developer"! I mainly use TYPO3 for my private website and working on some really simple extensions, for (partly private and therefore hidden) use on that website. 
@liayn and @simonschaufi: Let's end discussion here and leave everything as @liayn has changed already.

**Comment by nicodh** [comment]
The problem with file upload is not only that FAL is not designed to be Extbase compatible, but even if we include @helhum  upload example we still have no implementation to remove FileReferences again. Or did I miss something?
To me it seems this is still at the same incomplete state as it was 5 years ago when FAL was introduced. The " @todo Implement this function" in https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Resource/FileReference.php#L415 is at least 5 years old...
It seems no one uses Extbase or TYPO3 to upload files...

**Comment by liayn** [comment]
The mentioned todo is actually wrong and not a problem. You should not delete a file reference if the file itself still exists.

**Comment by simonschaufi** [comment]
@nicodh :laughing: I also have the feeling. It's so complicated :laughing:

**Comment by nicodh** [comment]
@liayn both cases can be useful: if there are multiple references to a file the file should not be deleted if a reference is deleted.
In fact it's possible to delete files:
$file->getOriginalResource()->getStorage()->deleteFile($file->getOriginalResource());
but not FileReferences... :-(

**Comment by simonschaufi** [comment]
@nicodh The general question for me would be if we should come up with a "basic file upload" so that users can for example upload an avatar because that is I guess a good use case for it or if we give the struggle to all the developers who will all look for a solution by themselves.

**Comment by nicodh** [comment]
I think that would help a lot of people. I already thought of someting like creating a  but to do it right we also should create Domain specific FileReference Model like in ://github.com/helhum/upload_example/blob/master/Classes/Domain/Model/FileReference.php. But to do it proper we should also create something like https://github.com/helhum/upload_example/blob/master/Classes/Property/TypeConverter/UploadedFileReferenceConverter.php which is far beyond the scope of an ExtensionBuilder. I think as long as there is no real solution in Extbase we can't do much...

**Comment by liayn** [comment]
@nicodh Of course you are totally right, My comment above was totally wrong. No idea what came to my mind three days ago.

**Comment by simonschaufi** [comment]
It looks like extbase needs some more :orange_heart:. I use Laravel intensively and file upload is so easy there but of course there is nothing like FAL. There you upload a file, it gets converted to a https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/UploadedFile.php object and then you can do everything you want.
