### ISSUE TITLE
v-10-compatibility - Error when saving a Model that maps to an existing table

### ISSUE THREAD

**Issue by Flimmerkiste** [FriendsOfTYPO3/extension_builder#315]
The commit at https://github.com/FriendsOfTYPO3/extension_builder/commit/de8b4eb978c64ef79cb803bef011da46834e68e3 introduces an issue when saving a model that maps to an existing table (pages in my case).

`Extension could not be saved: Could not generate TCA files, error: No class name was given to retrieve the Data Map for./var/www/html/web/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php`

![Bildschirmfoto 2020-09-23 um 12 11 31](https://user-images.githubusercontent.com/3634617/93999674-66cf3a00-fd96-11ea-8fe8-c0c88e61bfc1.png)

**Comment by nicodh** [comment]
It's not possible to map to the pages table. Since the ExtensionBuilder uses SingleTableInheritance the record type depends on the configured type field which is doktype and used for other purposes.
You should have seen a message: "The configuration for table "pages" is not compatible
with extbase. You have to configure it yourself if you want to map
to this table "

**Comment by nicodh** [comment]
Added a patch to avoid the error though
