### ISSUE TITLE
Add missing labels of plugin name and description

### ISSUE THREAD

**Issue by alexander-nitsche** [FriendsOfTYPO3/extension_builder#529]
**Describe the bug**
When creating frontend plugins using the Extension Builder, the two language file labels

- `LLL:EXT:<extension_name>/Resources/Private/Language/locallang_db.xlf:tx_<extension_name>_<plugin_name>.name`
- `LLL:EXT:<extension_name>/Resources/Private/Language/locallang_db.xlf:tx_<extension_name>_<plugin_name>.description`

are stored in the `ext_localconf.php` file for the plugin, but not created in `locallang_db.xlf`, i.e. in the content element wizard in the TYPO3 backend only the plugin icon is displayed, but name and description are missing.

**To Reproduce**
1. Go to Extension Builder.
2. Enter required meta data of extension.
3. Add dummy frontend plugin with proper name and description.
4. Save extension.
5. Install extension.
6. Go to content element wizard and verify that name and description of new plugin type are missing.

**Expected behavior**
Displayed plugin name and description should match name and description of the Extension Builder properties form.

**Screenshots**
![image](https://user-images.githubusercontent.com/20297232/141751362-d6067440-2c99-46d8-ab54-f598fce1f1d8.png)

**TYPO3 Version**
Current master (v11).

**Extension Builder Version:**
Current master (v11).

**Comment by knbknb** [comment]
I have the same problem.   
Indeed it is very annoying and itme-consuming to find all this out. Jjump around in the extension directoy, then compare with other extensions ...), and then add the XML fragments to the respective `.xlf` file.  
TYPO3 10.4.21, Extension Builder 10.0.2, installed with composer.

**Comment by simonschaufi** [comment]
@knbknb Maintaining this extension is also very time-consuming, by the way ;) Have you considered donating or contributing to help me maintain this extension? That would mean a lot!

**Comment by knbknb** [comment]
@simonschaufi I know that this is very time-consuming. Thank you for your efforts. It was nothing personal. It is great that you do all this work. Extension-Builder is essential for any serious work with TYPO3.

However, I have just started working with the Fluid-based Extension-Builder. The idea of me going through the source code to fix this bug is unthinkable, at this time.  Sorry. I am working on a delayed project that I do not want to work on in the first place. 

I am just saying that this misfeature is particularly off-putting. 

From my perspective it looks like this:  
Do the modeling. Save extension. Click thorough a lot of nag-screens and warning dialogs (which are justified and should remain). Composer this, typo3cms that. Load extension with Info/Modify tab. Open "+ Content Element" dialog, aaaaand ... the labels are not there, in the Plugins tab (see screenshot of OP).  Especially confusing when you have an extension with several plugins. Which icon correspnds to what?

Surely it is my fault ... I must have forgotten something .... Do the same thing again, modify my new extension. Try camelCase here, remove a blank there. Save again. Still no labels. Start with directory-diffs, then file-diffs .... and so on and on...
