### ISSUE TITLE
🐛 [BUG] Typed property EBT\ExtensionBuilder\Controller\BuilderModuleController::$moduleTemplateFactory must not be accessed before initialization

### ISSUE THREAD

**Issue by marten66** [FriendsOfTYPO3/extension_builder#660]
I got this error when i start the Exension-Builder in the admin panel:
Typed property EBT\ExtensionBuilder\Controller\BuilderModuleController::$moduleTemplateFactory must not be accessed before initialization

**TYPO3 Version**
11.5.32

**Extension Builder Version:**
11.0.9

**Comment by PKuhlmay** [comment]
Hi @marten66 do you get this error in version 11.0.10 of the EB too? You can download it directly from GitHub Repository, it is not available in TER at the moment (because of some issues with the TER in the past)

And which PHP version are you using?

Can you share some screenshot with the error? Maybe there are some more information which can help me. Especially the line number where the error occurs.

And did you mean "admin panel" or the "admin tools" ?

**Comment by PKuhlmay** [comment]
This should be fixed in TYPO3 12. Version v12.0.0-alpha.1
